export enum Key {
  Space = ' ',
  Escape = 'Escape',
  Enter = 'Enter',
  ArrowUp = 'ArrowUp',
  ArrowDown = 'ArrowDown',
  ArrowRight = 'ArrowRight',
  ArrowLeft = 'ArrowLeft',
  z = 'z',
  q = 'q',
  s = 's',
  d = 'd',
  a = 'a',
  e = 'e',
}
